game:
  arch: auto
  exe: /home/hypeit/Games/Torchlight 3/Frontiers.exe
  prefix: ~/.wine
  working_dir: ~/Games/Torchlight 3
system:
  disable_runtime: false
  dri_prime: false
  env: {}
  game_path: ~/Games/Torchlight 3
  prefer_system_libs: true
  prefix_command: ''
  prelaunch_command: ''
  prime: false
  resolution: 1366x768
  vk_icd: /usr/share/vulkan/icd.d/nvidia_icd.json
wine:
  Desktop: true
  WineDesktop: 1366x768
  d3d_extras: true
  dxvk: true
  dxvk_nvapi: true
  dxvk_version: v1.9.2L-3e64e1b
  esync: true
  fsync: true
  show_debug: -all
  system_winetricks: true
  version: lutris-ge-7.0rc3-1-x86_64
  vkd3d: true
